### ISSUE TITLE
Execute plans in Android

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/KotlinSyft#32]
This epic issue is somewhat self-explanatory, but in theory, we need to be able to execute a PySyft plan. This should ideally only be done after the API has been finalized in the Android worker (https://github.com/OpenMined/KotlinSyft/issues/23).
- [x] `implement retrofit HTTP ` #46 
- [x] `download plan via Http`
- [x] `Generate torchscript file from plan`
- [x] `Run the torchscript in compute thread` #69 
- [x] `Submit the diff to PyGrid`

**Comment by vkkhare** [comment]
@all-contributors please add @vkkhare for code

**Comment by vkkhare** [comment]
@all-contributors please add @IamRavikantSingh for coding

**Comment by vkkhare** [comment]
@all-contributors please add @vkkhare  for coding
