### ISSUE TITLE
Create the syft configuration class

### ISSUE THREAD

**Issue by vkkhare** [OpenMined/KotlinSyft#53]
This class would provide the base methods/configs for downloading, training and uploading to ensure the developer using KotlinSyft adheres to best practices to prevent the owner of the mobile from getting drained out of his battery/monetary resources.

**Comment by vkkhare** [comment]
- [ ] add configuration for `destinationDirectory` of the downloads
- [ ] add configuration for job computation scheduler
- [ ] add configuration for networking scheduler
